# This code is to print the receipt for Hab Taxi Services.

#print

print()
print(f"-------------------------------------------------------------------------------")
print(f"                           HAB TAXI SERVICES                                   ")
print(f"                         Rental/Payment Receipt                                ")
print(f"-------------------------------------------------------------------------------")
print(                                                                                  )
print(f"Date:                    [Current Date]                                        ")
print(f"Receipt ID:              [Auto-generated ID]                                   ")
print(                                                                                  )
print(f"Driver Information:                                                            ")
print(f"Driver Name:             [Employee Name]                                       ")
print(f"Driver Number:           [Employee Number]                                     ")
print(f"Phone Number:            [Employee Phone Number]                               ")
print(                                                                                  )
print(f"-------------------------------------------------------------------------------")
print(                                                                                  )
print(f"Transaction Details:                                                           ")
print(                                                                                  )
print(f"Reason for Receipt:      [Rental / Payment]                                    ")
print(f"Description:             [Details of rental or payment]                        ")
print(f"Amount:                  $[Amount]                                             ")
print(f"HST:                     $[HST Amount]                                         ")
print(f"Total:                   $[Total Amount]                                       ")
print()
print(f"Payment Method:          [Cash / Debit / Visa]                                 ")
print()
print(f"-------------------------------------------------------------------------------")
print(f"Thank you for your business!                                                   ")
print(f"For inquiries, please contact us at [Contact Information].                     ")
print(f"-------------------------------------------------------------------------------")
print()